# -*- coding: utf-8 -*-
"""Image_processing_enhancement_techniques.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uDXx1LO9uMZMO1ZGA5IiRvtEQP5h_khi
"""

!pip install opencv-python

import cv2

img = cv2.imread('peacock.jpg')

print(img)

import matplotlib.pyplot as plt
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img_rgb)
plt.axis('off')

img.shape

img_bgr = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)

import matplotlib.pyplot as plt

plt.imshow(img_bgr)
plt.axis('off')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

import matplotlib.pyplot as plt

plt.imshow(gray, cmap='gray')
plt.axis('off')

print(gray)

hist = cv2.calcHist([gray], [0], None, [256], [0, 256])

plt.plot(hist)
plt.xlabel('Pixel Intensity')
plt.ylabel('Number of Pixels')
plt.title('Grayscale Image Histogram')
plt.show()

negative = 255 - img_rgb

plt.imshow(negative)
plt.title("Negative Image")
plt.axis('off')

equalized = cv2.equalizeHist(gray)

plt.imshow(equalized, cmap='gray')
plt.title("Histogram Equalized Image")
plt.axis('off')

laplacian = cv2.Laplacian(gray, cv2.CV_64F)
sharpened = cv2.convertScaleAbs(gray - laplacian)

plt.imshow(sharpened, cmap='gray')
plt.title("Sharpened Image")
plt.axis('off')

mean_filter = cv2.blur(gray, (5,5))

plt.imshow(mean_filter, cmap='gray')
plt.title("Mean Filtered Image")
plt.axis('off')

laplacian = cv2.Laplacian(gray, cv2.CV_64F)
laplacian = cv2.convertScaleAbs(laplacian)

enhanced = cv2.subtract(gray, laplacian)

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.imshow(gray, cmap='gray')
plt.title("Original Grayscale")
plt.axis('off')

plt.subplot(1,2,2)
plt.imshow(enhanced, cmap='gray')
plt.title("Edge Enhanced Image")
plt.axis('off')

plt.show()